---
- hosts: all
  sudo: yes
  tasks: 
    - name: ensure Postgres packages are installed
      apt: name={{item}}
      with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

- hosts: all
  sudo: yes
  sudo_user: postgres

  vars:
    dbname: myapp
    dbuser: philip
    dbpassword: supersecret

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privileges
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

  - name: ensure user has password verification for psql cli access
    lineinfile: dest=/etc/postgresql/9.1/main/pg_hba.conf
      regexp='^#?local all {{dbuser}}\s*'
      line='local all {{dbuser}} md5'
      state=present
    notify: restart postgresql

  - name: ensure postgres is started and enabled at boot
    service: name=postgresql
             enabled=yes
             state=started

  handlers:
  - name: restart postgresql
    service: name=postgresql state=restarted