--- 
- name: install hsqldb 
  apt: name=hsqldb state=present  

- name: hsqldb config change 
  lineinfile: dest=/etc/sysconfig/hsqldb line="JAVA_HOME={{ JAVA_HOME }}" insertafter="^JAVA_HOME=\$.*\n" 

- name: hsqldb config change 
  lineinfile: dest=/etc/sysconfig/hsqldb line="HSQLDB_JAR_PATH=/usr/share/java/hsqldb.jar" insertafter="^HSQLDB_JAR_PATH=\$.*\n" 
 
- name: start hsqldb 
  service: name=hsqldb state=restarted 
